-- II
DROP TABLESPACE sql3_tbs
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP TABLESPACE sql3_temptbs
INCLUDING CONTENTS AND DATAFILES
CASCADE CONSTRAINTS;

DROP USER sql3 CASCADE;

----

CREATE TABLESPACE sql3_tbs
DATAFILE 'c:\sql3_tbs.dbf'
SIZE 50M
AUTOEXTEND ON;

CREATE TEMPORARY TABLESPACE sql3_temptbs
TEMPFILE 'c:\sql3_temptbs.dbf'
SIZE 50M
AUTOEXTEND ON;

CREATE USER sql3
IDENTIFIED BY zerty
DEFAULT TABLESPACE sql3_tbs
TEMPORARY TABLESPACE sql3_temptbs
QUOTA UNLIMITED ON sql3_tbs;

GRANT ALL PRIVILEGES
TO sql3;
